{{- $service := .Values.services.userService }}

apiVersion: v1
kind: Service
metadata:
  name: "user-service"
  labels:
    app: "user-service"
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: "user-service"
  env:
    - name: ENVIRONMENT
      value: {{ $.Values.environment }}
