# ค่าทั่วไป
environment: "default"
replicaCount: 1
secretKey: "d0X4R9u9aB8Gq7tZx3vH2mKfQyP1jL6E" # ควรเปลี่ยน หรือใช้ --set ตอนติดตั้ง

# การตั้งค่า Image
image:
  # ตัวอย่าง: my-registry/user-service
  # ถ้าไม่ได้ระบุ registry จะใช้ Docker Hub
  registry: "endy95" 
  pullPolicy: IfNotPresent

service:
  # กำหนดค่าสำหรับแต่ละ Service
  userService:
    enabled: true
    image:
      repository: user_service
      tag: "latest"
    port: 8001
    targetPort: 8000
    database:
      host: "mongo-users"
      port: 27017
    resources:
      requests:
        cpu: "100m"     # ร้องขอ CPU 0.1 core (100 millicores)
        memory: "128Mi" # ร้องขอ Memory 128 Mebibytes
      limits:
        cpu: "500m"     # จำกัด CPU ไม่เกิน 0.5 core
        memory: "512Mi" # จำกัด Memory ไม่เกิน 512 Mebibytes

# กำหนดค่าสำหรับ MongoDB StatefulSets
mongo:
  image:
    repository: mongo
    tag: "6.0"
  storage:
    size: 1Gi
  users:
    enabled: true