{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- toYaml .hosts | nindent 8 }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{ if .host }}
      host: {{ .host | quote }}
      {{ end }}
      http:
        paths:
          {{- range .paths }}
            {{- $servicePort := .port }}
          - path: {{ .path }}
            pathType: Prefix # ใช้ Prefix หรือ Exact ตามความเหมาะสม
            backend:
              service:
                name: {{ .service | lower }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
  env:
    - name: ENVIRONMENT
      value: {{ $.Values.environment }}
{{- end }}