apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Endy74757/expense-tracker-devops.git
    chart: charts/ingress
    targetRevision: dev # ระบุเวอร์ชันเพื่อความเสถียร
    helm:
      valueFiles:
        - argocd/dev/ingress/values-dev.yaml # ใช้ values สำหรับ dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true