# ค่าทั่วไป
replicaCount: 1
secretKey: "d0X4R9u9aB8Gq7tZx3vH2mKfQyP1jL6E" # ควรเปลี่ยน หรือใช้ --set ตอนติดตั้ง

# การตั้งค่า Image
image:
  # ตัวอย่าง: my-registry/user-service
  # ถ้าไม่ได้ระบุ registry จะใช้ Docker Hub
  registry: "endy95" 
  pullPolicy: IfNotPresent

services:
  # กำหนดค่าสำหรับแต่ละ Service
  userService:
    enabled: true
    image:
      repository: user_service
      tag: "dev" # Tag สำหรับ dev
    port: 8001
    targetPort: 8000
    database:
      host: "mongo-users"
      port: 27017
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  transactionService:
    enabled: true
    image:
      repository: transaction_service
      tag: "dev" # Tag สำหรับ dev
    port: 8002
    targetPort: 8000
    database:
      host: "mongo-transactions"
      port: 27017
    resources:
      requests:
          cpu: "100m"
          memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  categoryService:
    enabled: true
    image:
      repository: category_service
      tag: "dev" # Tag สำหรับ dev
    port: 8003
    targetPort: 8000
    database:
      host: "mongo-categories"
      port: 27017
    resources:
      requests:
          cpu: "100m"
          memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

# กำหนดค่าสำหรับ MongoDB StatefulSets
mongo:
  image:
    repository: mongo
    tag: "6.0"
  storage:
    size: 1Gi
  users:
    enabled: true
  categories:
    enabled: true
  transactions:
    enabled: true

# กำหนดค่าสำหรับ Ingress
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: /users(/|$)(.*)
          service: userService
        - path: /transactions(/|$)(.*)
          service: transactionService
        - path: /categories(/|$)(.*)
          service: categoryService